#!/usr/bin/with-contenv bash

mkdir -p \
    /config/phpmyadmin \
    /app/www/public/tmp

if [ ! -f /config/phpmyadmin/config.secret.inc.php ]; then
    cat > /config/phpmyadmin/config.secret.inc.php <<EOT
<?php
\$cfg['blowfish_secret'] = '$(tr -dc 'a-zA-Z0-9~!@#$%^&*_()+}{?></";.,[]=-' < /dev/urandom | fold -w 32 | head -n 1)';
EOT
fi

if [ ! -f /config/phpmyadmin/config.user.inc.php ]; then
    touch /config/phpmyadmin/config.user.inc.php
fi

if [ ! -f /config/phpmyadmin/config.inc.php ]; then
    cp /defaults/config.inc.php /config/phpmyadmin/config.inc.php
fi

lsiown -R abc:abc \
    /config \
    /app/www/public/tmp
